In [1]:
# Import numpy
import numpy as np

In [6]:
# Create a numpy array with single value
age =32
np_array = np.array(age)
print(type(np_array))
print(np_array)
print(np_array.ndim)

<class 'numpy.ndarray'>
32
0


In [7]:
# Create a numpy array with multiple values
age = [32,26,28,34]
np_array = np.array(age)
print(np_array)
print(np_array.ndim)

[32 26 28 34]
1


In [9]:
# Create a numpy array with group of values
age = [[26,28,24],[32,35,34]]
np_array = np.array(age)
print(np_array)
print(np_array.ndim)

[[26 28 24]
 [32 35 34]]
2


In [15]:
# Access values from numpy array
for i in range(np_array.ndim):
    print()
    for j in np_array[i]:
        print(j,end = " ")


26 28 24 
32 35 34 

In [27]:
#  Create a 3*3 matrix and access elements from the matrix using numpy array
age = [[22,25,24],[30,35,32],[48,46,41]]
np_array = np.array(age)
print(np_array[1,1])
print(np_array[2,0])

35
48


In [30]:
# Create numpy array with all zeros
np_zero_array = np.zeros(4)
print(np_zero_array)

[0. 0. 0. 0.]


In [31]:
np_ones_arr = np.ones(6)
print(np_ones_arr)

[1. 1. 1. 1. 1. 1.]


In [38]:
age = [[22,25,24],[30,35,32],[48,46,41]]
np_array = np.array(age)
print(np.shape(np_array))
print(np.shape(np_array)[0])
print(np.ndim(np_array))

(3, 3)
3
2


In [42]:
# Transpose a matrix using 'T' attribute
age = [[22,25],[35,32],[46,41]]
np_array = np.array(age)
print("Original Matrix")
print(np_array)
print("Transpose Matrix")
print(np_array.T)

Original Matrix
[[22 25]
 [35 32]
 [46 41]]
Transpose Matrix
[[22 35 46]
 [25 32 41]]


In [46]:
age = [[22,25],[35,32],[46,41]]
np_array = np.array(age)
print(np_array.min())
print(np_array.min(axis=1))
print(np_array.min(axis=0))

22
[22 32 41]
[22 25]


In [47]:
age = [[22,25],[35,32],[46,41]]
np_array = np.array(age)
print(np_array.max())
print(np_array.max(axis=1))
print(np_array.max(axis=0))

46
[25 35 46]
[46 41]


In [49]:
age = [[22,25],[35,32],[46,41]]
np_array = np.array(age)
print(np_array.sum())
print(np_array.sum(axis=1))
print(np_array.sum(axis=0))

201
[47 67 87]
[103  98]


In [55]:
age = [[22,25],[35,32],[46,41],[26,28],[39,38]]
np_array = np.array(age)
print(np_array)
print(np_array.reshape(2,5))
print(np_array.reshape(1,10))

[[22 25]
 [35 32]
 [46 41]
 [26 28]
 [39 38]]
[[22 25 35 32 46]
 [41 26 28 39 38]]
[[22 25 35 32 46 41 26 28 39 38]]


In [70]:
age = [[22,0],[35,-32],[46,41]]
np_array = np.array(age)
print(np.nonzero(np_array))
print(np.count_nonzero(np_array))
np_array.sort()
print(np_array)
np_array.sort(axis=0)
print(np_array)

(array([0, 1, 1, 2, 2], dtype=int64), array([0, 0, 1, 0, 1], dtype=int64))
5
[[  0  22]
 [-32  35]
 [ 41  46]]
[[-32  22]
 [  0  35]
 [ 41  46]]


In [87]:
#  Add value to array elements
age = [[22,25],[35,32],[46,41]]
np_array = np.array(age)
print(np_array)

np_array = np_array+2  # Add 2 to each array element
print(np_array)

print(np_array.diagonal())  # Diagonal elements of a matrix
print(f'Sum of diagonal: {sum(np_array.diagonal())}')
print(f'Trace of matrix: {np_array.trace()}')    # Trace of a matrix

[[22 25]
 [35 32]
 [46 41]]
[[24 27]
 [37 34]
 [48 43]]
[24 34]
Sum of diagonal: 58
Trace of matrix: 58


In [93]:
#  Add 2 matrices
matrix_a = [[22,25],[35,32],[46,41]]
matrix_b = [[10,12],[4,5],[4,9]]
np_array_a = np.array(matrix_a)
np_array_b = np.array(matrix_b)

print(np_array_a+np_array_b)

np_array_add = np.add(np_array_a,np_array_b)
print(np_array_add)

[[32 37]
 [39 37]
 [50 50]]
[[32 37]
 [39 37]
 [50 50]]


In [94]:
#  Subtract 2 matrices values
matrix_a = [[22,25],[35,32],[46,41]]
matrix_b = [[10,12],[4,5],[4,9]]
np_array_a = np.array(matrix_a)
np_array_b = np.array(matrix_b)

print(np_array_a-np_array_b)

np_array_sub = np.subtract(np_array_a,np_array_b)
print(np_array_sub)

[[12 13]
 [31 27]
 [42 32]]
[[12 13]
 [31 27]
 [42 32]]
